[[users]]
name = "test_name"
gender = "male"
email = ""
status = "active"

[[users]]
name = "Ekaaksh Gowda"
email = ""
gender = "male"
status = "inactive"

[[users]]
name = "Aagam Chaturvedi"
email = ""
gender = "female"
status = "inactive"

[[to_update]]
name = "Hornet"

[[to_update]]
email = "test@test.com"

[[to_update]]
gender = "female"

[[to_update]]
status = "inactive"