[[comments]]
post_id = 1_688
name = "Prof. Veda Varrier"
email = ""
body = "In velitus earum. Velit odit et."

[[comments]]
post_id = 1_607
name = "Tara Iyer II"
email = ""
body = "Nostrum qui doloribus."

[[comments]]
post_id = 1_607
name = "Prasad Ahuja"
email = ""
body = "Eveniet facere ea. Atque voluptas ut."

[[comments]]
post_id = 1_598
name = "The Hon. Kama Prajapat"
email = ""
body = "Distinctio sunt repellendus. Deserunt amet delectus."

[[comments]]
post_id = 1_598
name = "Jagmeet Abbott"
email = ""
body = "Soluta consequatur ex. Doloribus vitae modi. Sunt quaerat similique."

[[comments]]
post_id = 1_595
name = "Malti Kaniyar"
email = ""
body = "Dolorem praesentium eos. Sed et ducimus. Provident modi rerum. Aliquid maiores maxime."

[[comments]]
post_id = 1_594
name = "Prathamesh Nehru VM"
email = ""
body = "Corrupti mollitia dolor. Itaque minima sit. Consequatur ut numquam."

[[comments]]
post_id = 1_594
name = "Dr. Shrishti Nambeesan"
email = ""
body = "Possimus modi aut."