[[users]]
name = "Sujata Shukla"
email = ""
gender = "female"
status = "inactive"

[[users]]
name = "Sher Jain"
email = ""
gender = "female"
status = "active"

[[todos]]
user_id = 3_304
title = "Decerno deleo sapiente tepidus talio."
due_on = "2022-07-19T00:00:00.000+05:30"
status = "completed"

[[todos]]
user_id = 3_271
title = "Summisse coaegresco totidem trans aut tamquam."
due_on = "2022-08-10T00:00:00.000+05:30"
status = "completed"